### PR TITLE
Add support for "human format"

### LINKED ISSUE #7: [Feature Request]Add support for taking space as delimiter or no specific delimiter characters
Accept input with spaces or no specific characters as delimiter. eg:
```text
17:02  Eternal Harmony	平山笑美, 雨宮天, 麻倉もも, 阿部里果, 村川梨衣
42:19 Princess Be Ambitious!!	山崎はるか, 郁原ゆう, 原嶋あかり, 伊藤美来, 村川梨衣, 木戸衣吹
58:10Angelic Parade♪	平山笑美, 香里有佐, 近藤唯, 末柄里恵, 小笠原早紀, 麻倉もも, 高橋未奈美
1:11:00.942  Come on a Tea Party!	麻倉もも
1:42:10.255FairyTaleじゃいられない	雨宮天, 南早紀, 渡部恵子, 戸田めぐみ, 阿部里果, 中村温姫
1:46:02 ZETTAI×BREAK!! トゥインクルリズム	トゥインクルリズム (原嶋あかり, 伊藤美来, 村川梨衣)
1:50:32  Marionetteは眠らない	山崎はるか, 郁原ゆう, 末柄里恵, 木戸衣吹, 中村温姫
2:30:41.155 Melty Fantasia	EScape (阿部里果, 南早紀, 雨宮天)
2:35:11.696はなしらべ	郁原ゆう
2:45:42 ココロがかえる場所	郁原ゆう, 香里有佐, 近藤唯, 戸田めぐみ
2:55:24  瑠璃色金魚と花菖蒲	南早紀
```
It's just the way people usually input timeline. For example, people usually type a timeline with such a format in comment zone. Human can recognize chapter with this format and so does program.

And with some little change, we can get a format that also contains `tab format` and `simple format`. A regex pattern can be
```python
r"(?P<time>[0-9]+:[0-9]{1,2}[0-9:.]*)([\s,]+(?P<name1>.+)|(?P<name2>[^\d:.\s,].+))"  # only one of name1 and name2 will be matched
```

### PR DESCRIPTION
**Pull request by Ethkuil**
close #7

### CODE REVIEW

**Comment by fireattack** [comment]
Thanks.

I can merge that if it only changes the regex to support "human format" up to https://github.com/fireattack/chapter_converter/pull/8/commits/9dff4f62a34bfc47738fa0cb7d54aeb81b5a87f4.

But I don't think it's a good idea to refractor it dramatically, especially when you introduce breaking change(s). 

And some syntax/style choices are intentional (e.g. keep all the functions in one file; use one-liner for argParser; not use walrus operator to be compatible with Py3.7 etc.).

**Comment by fireattack** [comment]
Anyway, my philosophy for a public-facing script is that, if it works fine, I will not refactor for the sake of it (it's super short either way).

But if you introduce major _features_ which benefits from refactoring, feel free to bring it in!

**Comment by fireattack** [comment]
Thanks!

I made some changes:

1. I don't want to mess with clipboard if an output is specified. So I reverted that part.
2. The "human format" regex is too relex IMO. Particularly, it shouldn't allow string that has no clear delimiter between timestamp and chapter name (e.g. `43:0001.chapter1`). It just asks for trouble. So I changed it to only accept string that are clearly separated by `\s+` or `\s*,\s*`.

**Comment by Ethkuil** [comment]
> 2\. The "human format" regex is too relex IMO. Particularly, it shouldn't allow string that has no clear delimiter between timestamp and chapter name (e.g. `43:0001.chapter1`). It just asks for trouble. So I changed it to only accept string that are clearly separated by `\s+` or `\s*,\s*`.

I don't think it just asks for trouble. Just as its name indicates, it **tries to deal with input manually inputted by human**(for example copied from the profile/a comment of a video). And **indeed I find several times that people write line like `23:10MC`**, and certainly other people can understand.

**Comment by fireattack** [comment]
I get that. I'm saying that's something the user needs to fix themselves. Because it could be ambiguous (43:00.121 chapter1 could be `43:00.12, 1 chapter 1` or `43:00.121, chapter 1`). I prefer throw error in such case rather than parse it in a way that may surprise the user. 

Also Just in case it's not clear. "Asks for trouble" is a figure of speech which means it is likely to incur problems in future. I'm not saying this feature itself is a "trouble".

**Comment by Ethkuil** [comment]
>  Because it could be ambiguous (43:00.121 chapter1 could be 43:00.12, 1 chapter 1 or 43:00.121, chapter 1). 

Is this case, the parsing result will be undoubtedly the same as `43:00.121, chapter 1`.

```python
HUMAN_RE = r"(?P<time>[0-9]+:[0-9]{1,2}[0-9:.]*)([\s,]+(?P<name1>.+)|(?P<name2>[^\d:.\s,].+))" # only one of name1 and name2 will be matched
```

It'll first look for `[\s,]+` as delimiters, and if found then it won't be ambiguous. If not found, then it'll try to take another character as the beginning of `name` part, and this character won't appear in `time` part or be common delimiters. It's `[^\d:.\s,]`. Maybe it's not ambiguous because there is always only one way to understand that makes sense for human.

**Comment by Ethkuil** [comment]
And certainly I agree that it should not be encouraged to use "no specific delimiter". But I think people won't write `43:00.121 chapter 1` and think it means `43:00.12,1 chapter 1`. So currently I don't worry about that.

If anything has been overlooked in error, please point it out.

**Comment by fireattack** [comment]
Any sane csv/tsv parser won't even allow more than one consistent delimiter throughout the file, and that's for a reason.

For example, with the existing code, the following two:
```
17:02\t,I'm a title started with a comma
```
```
17:02,,I'm a title started with a comma
```
will be correctly recognized as name = `,I'm a title started with a comma`. But the regex you provided will dismiss the leading comma.

A  more tricker case is names start with a space. The old SIMPLE_RE indeed can't deal with it either (since I use `, *`), but if the user feed in a file that is properly delimited with tab, it can have leading space in names, too.

Of course, one can always argue which use case is more "common"; but the bottom line is, people who use the more "standard" format shouldn't be punished. 


Anyway, here is my final compromise: 
* I will allow no delimiter.
* I will sacrifice the support for having leading space in tab-delimited format.
* But if you want to delimit the input with comma, it must be immediately after the timestamp, just like before. This way, things like
```
17:02,,I'm a title started with a comma
17:02\t,I'm a title started with a comma
```
will still be recognized as name = `,I'm a title started with a comma`.

The new regex is

```python
(?P<time>\d+:\d{1,2}[0-9:.]*)(,?\s*)(?P<name>.+)
```

You don't really need the name2 part. Because the front/left parts are all greedy, they will match up to the delimiter just fine. `[^\d:.\s,]` isn't needed.

Please let me know what you think before we merge.

**Comment by Ethkuil** [comment]
It's a perfect solution for me😄. Thank you for your patience.

**Pull request merged**
